'use client';
import Link from 'next/link';
import { rupiah, type Attendance, type InventoryItem, type Recipe, type Task, type Transaction } from '@/lib/mock/rileks-data';
import { summarize, type RileksState } from '@/lib/mock/rileks-store';
export function MockDataNotice(){return <div className="pill" style={{background:'#fff7ed'}}>Demo mockup — data simulasi, belum terhubung ke WhatsApp/database.</div>}
export function DashboardCard({label,value,note}:{label:string;value:string|number;note?:string}){return <div className="card"><div className="muted">{label}</div><div className="stat">{value}</div>{note&&<div className="muted">{note}</div>}</div>}
export function StatusBadge({status}:{status:string}){const c=status.includes('Aman')||status.includes('Masuk')||status.includes('Selesai')?'ok':status.includes('Habis')?'bad':'warn';return <span className={`badge ${c}`}>{status}</span>}
export function AppShell({children}:{children:React.ReactNode}){const links=[['/dashboard','Dashboard'],['/dashboard/absensi','Absensi'],['/dashboard/tasks','Daily Task'],['/dashboard/resep','Resep'],['/dashboard/inventori','Inventori'],['/dashboard/keuangan','Keuangan'],['/demo','Demo']];return <div className="shell"><aside className="side"><Link href="/" className="brand" style={{color:'#fff'}}>Rileks</Link><p style={{color:'#bdebd8'}}>Control room ringan untuk outlet F&B.</p><nav>{links.map(([h,l])=><Link key={h} href={h}>{l}</Link>)}</nav></aside><main className="main">{children}</main></div>}
export function SummaryCards({state}:{state:RileksState}){const s=summarize(state);return <div className="grid summary"><DashboardCard label="Staff masuk hari ini" value={s.staffIn}/><DashboardCard label="Tugas selesai" value={`${s.tasksDone}/${state.tasks.length}`}/><DashboardCard label="Stok menipis" value={s.lowStock}/><DashboardCard label="Penjualan hari ini" value={rupiah(s.sales)}/><DashboardCard label="Pengeluaran hari ini" value={rupiah(s.expense)}/><DashboardCard label="Closing cash terakhir" value={rupiah(s.closing)}/></div>}
export function ActivityFeed({items}:{items:string[]}){return <div className="card"><h3>Aktivitas terbaru</h3>{items.map((i,idx)=><p key={idx}>• {i}</p>)}</div>}
export function AttentionList(){return <div className="card"><h3>Yang perlu perhatian</h3><p>⚠️ Minyak mendekati minimum</p><p>⚠️ Sari belum check-in</p><p>⚠️ Closing kemarin belum lengkap</p></div>}
export function AttendanceTable({rows}:{rows:Attendance[]}){return <div className="card"><table><thead><tr><th>Staff</th><th>Role</th><th>Outlet</th><th>Masuk</th><th>Pulang</th><th>Status</th><th>Lokasi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.staff}</td><td>{r.role}</td><td>{r.outlet}</td><td>{r.checkIn||'-'}</td><td>{r.checkOut||'-'}</td><td><StatusBadge status={r.status}/></td><td>{r.location}</td></tr>)}</tbody></table></div>}
export function TaskChecklist({tasks}:{tasks:Task[]}){return <div className="card"><table><tbody>{tasks.map(t=><tr key={t.id}><td>{t.done?'✅':'⬜'} {t.name}</td><td>{t.role}</td><td>{t.completedBy||'-'}</td><td>{t.time||'-'}</td></tr>)}</tbody></table></div>}
export function RecipeCard({recipe}:{recipe:Recipe}){return <div className="card"><h3>{recipe.name}</h3><StatusBadge status={recipe.active?'Aktif':'Nonaktif'}/><p className="muted">{recipe.category}</p><b>Bahan</b>{recipe.ingredients.map(i=><p key={i}>• {i}</p>)}<b>Langkah</b><p>{recipe.steps}</p></div>}
export function InventoryStatusTable({items}:{items:InventoryItem[]}){return <div className="card"><table><thead><tr><th>Item</th><th>Stok</th><th>Minimum</th><th>Status</th><th>Update</th></tr></thead><tbody>{items.map(i=>{const st=i.stock<=0?'Habis':i.stock<=i.minimum?'Menipis':'Aman';return <tr key={i.id}><td>{i.name}</td><td>{i.stock} {i.unit}</td><td>{i.minimum} {i.unit}</td><td><StatusBadge status={st}/></td><td>{i.updated}</td></tr>})}</tbody></table></div>}
export function FinanceSummary({transactions}:{transactions:Transaction[]}){const sales=transactions.filter(t=>t.type==='sales').reduce((a,t)=>a+t.amount,0);const exp=transactions.filter(t=>t.type==='expense').reduce((a,t)=>a+t.amount,0);return <><div className="grid summary"><DashboardCard label="Penjualan" value={rupiah(sales)}/><DashboardCard label="Pengeluaran" value={rupiah(exp)}/><DashboardCard label="Net cash" value={rupiah(sales-exp)}/></div><div className="card"><table><tbody>{transactions.map(t=><tr key={t.id}><td>{t.time}</td><td>{t.label}</td><td>{t.type}</td><td>{rupiah(t.amount)}</td></tr>)}</tbody></table></div></>}
